# Generated by Django 5.0.1 on 2024-02-03 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0009_chat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='number_or_bids',
            new_name='number_of_bids',
        ),
    ]
