# Generated by Django 5.0.1 on 2024-02-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0010_rename_number_or_bids_auction_number_of_bids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='time_ending',
            field=models.TimeField(),
        ),
    ]
