# Generated by Django 5.0.1 on 2024-02-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0011_alter_auction_time_ending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='time_ending',
            field=models.DateTimeField(),
        ),
    ]
