# Generated by Django 5.0.1 on 2024-03-05 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0013_auction_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='time_ending',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
