# Generated by Django 5.0.1 on 2024-03-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0014_alter_auction_time_ending'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='base_price',
            field=models.IntegerField(null=True),
        ),
    ]
