# Generated by Django 5.0.1 on 2024-03-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0015_auction_base_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='base_price',
            field=models.FloatField(null=True),
        ),
    ]
