# Generated by Django 5.0.1 on 2024-03-17 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0016_alter_auction_base_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
