# Generated by Django 5.0.1 on 2024-03-17 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0017_delete_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
