# Generated by Django 5.0.1 on 2024-03-17 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0018_remove_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
