# Generated by Django 5.0.1 on 2024-03-20 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0023_rename_product_name_auction_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='auction_id',
            new_name='auction',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='user_id',
            new_name='user',
        ),
    ]
