# Generated by Django 5.0.1 on 2024-03-20 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0024_rename_auction_id_watchlist_auction_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='auction_id',
            new_name='auction',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='user_id',
            new_name='user',
        ),
    ]
