# Generated by Django 5.0.1 on 2024-03-23 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0026_auction_final_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='balance',
        ),
    ]
