# Generated by Django 5.0.1 on 2024-03-24 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0028_rename_userdetails_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='final_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
