# Generated by Django 5.0.1 on 2024-03-24 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0029_alter_auction_base_price_alter_auction_final_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='cellphone',
            new_name='phone',
        ),
    ]
