# Generated by Django 5.0.1 on 2024-03-24 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0030_rename_cellphone_userinfo_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='number_of_bids',
            new_name='count_bids',
        ),
    ]
