# Generated by Django 5.0.1 on 2024-03-24 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0031_rename_number_of_bids_auction_count_bids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='time_starting',
            new_name='time_start',
        ),
    ]
