# Generated by Django 5.0.1 on 2024-03-24 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0032_rename_time_starting_auction_time_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='time_ending',
            new_name='time_end',
        ),
    ]
