# Generated by Django 5.0.1 on 2024-03-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0033_rename_time_ending_auction_time_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='price_per_bid',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
