# Generated by Django 5.0.1 on 2024-03-30 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0034_auction_price_per_bid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
